version: 2
services:
  web:
    # Specify your preferred Node.js version
    image: node:14

    # Install dependencies and Playwright
    buildScript: |
      npm ci
      npm install -g playwright
      npx playwright install --with-deps --path C:\Users\hp\Documents\GitHub\scraping-bot\browsers

    # Define the default command to run when the container starts
    startCommand: npm start
