version: 2
services:
  web:
    # Specify your preferred Node.js version
    image: node:14

    # Install dependencies and Playwright
    buildScript: |
      npm ci
      npm install -g playwright
      npx playwright install

    # Set environment variable for Chromium executable path
    environment:
      CHROMIUM_EXECUTABLE_PATH: "$(which chromium)"

    # Define the default command to run when the container starts
    startCommand: npm start
